export const movies = [
    /* Top Picks */
    {
        movie_aid: 1,
        movie_title: "Missed Connection",
        movie_year: "2024",
        movie_duration: "1hr 50mins",
        movie_category: "Top Picks",
        movie_genre: "Drama, Romance",
        movie_summary: "After an unforgettable encounter, a hopeless romantic turns to an app to seek out a man she just met - but is he really what she's looking for?",
        movie_cast: "Miles Ocampo, Kelvin Miranda,  Chienna Filomeno",
        movie_rating: "R-20+",
        movie_image: "slider-5.webp",
        movie_is_active: true,
    },
    {
        movie_aid: 2,
        movie_title: "Missed Connection",
        movie_year: "2024",
        movie_duration: "1hr 50mins",
        movie_category: "Top Picks",
        movie_genre: "Drama, Romance",
        movie_summary: "After an unforgettable encounter, a hopeless romantic turns to an app to seek out a man she just met - but is he really what she's looking for?",
        movie_cast: "Miles Ocampo, Kelvin Miranda,  Chienna Filomeno",
        movie_rating: "R-20+",
        movie_image: "slider-5.webp",
        movie_is_active: true,
    },
    {
        movie_aid: 3,
        movie_title: "Missed Connection",
        movie_year: "2024",
        movie_duration: "1hr 50mins",
        movie_category: "Top Picks",
        movie_genre: "Drama, Romance",
        movie_summary: "After an unforgettable encounter, a hopeless romantic turns to an app to seek out a man she just met - but is he really what she's looking for?",
        movie_cast: "Miles Ocampo, Kelvin Miranda,  Chienna Filomeno",
        movie_rating: "R-20+",
        movie_image: "slider-5.webp",
        movie_is_active: true,
    },
    {
        movie_aid: 4,
        movie_title: "Missed Connection",
        movie_year: "2024",
        movie_duration: "1hr 50mins",
        movie_category: "Top Picks",
        movie_genre: "Drama, Romance",
        movie_summary: "After an unforgettable encounter, a hopeless romantic turns to an app to seek out a man she just met - but is he really what she's looking for?",
        movie_cast: "Miles Ocampo, Kelvin Miranda,  Chienna Filomeno",
        movie_rating: "R-20+",
        movie_image: "slider-5.webp",
        movie_is_active: true,
    },
    {
        movie_aid: 5,
        movie_title: "Missed Connection",
        movie_year: "2024",
        movie_duration: "1hr 50mins",
        movie_category: "Top Picks",
        movie_genre: "Drama, Romance",
        movie_summary: "After an unforgettable encounter, a hopeless romantic turns to an app to seek out a man she just met - but is he really what she's looking for?",
        movie_cast: "Miles Ocampo, Kelvin Miranda,  Chienna Filomeno",
        movie_rating: "R-20+",
        movie_image: "slider-5.webp",
        movie_is_active: true,
    },
    {
        movie_aid: 6,
        movie_title: "Missed Connection",
        movie_year: "2024",
        movie_duration: "1hr 50mins",
        movie_category: "Top Picks",
        movie_genre: "Drama, Romance",
        movie_summary: "After an unforgettable encounter, a hopeless romantic turns to an app to seek out a man she just met - but is he really what she's looking for?",
        movie_cast: "Miles Ocampo, Kelvin Miranda,  Chienna Filomeno",
        movie_rating: "R-20+",
        movie_image: "slider-5.webp",
        movie_is_active: true,
    },
    {
        movie_aid: 7,
        movie_title: "Missed Connection",
        movie_year: "2024",
        movie_duration: "1hr 50mins",
        movie_category: "Top Picks",
        movie_genre: "Drama, Romance",
        movie_summary: "After an unforgettable encounter, a hopeless romantic turns to an app to seek out a man she just met - but is he really what she's looking for?",
        movie_cast: "Miles Ocampo, Kelvin Miranda,  Chienna Filomeno",
        movie_rating: "R-20+",
        movie_image: "slider-5.webp",
        movie_is_active: true,
    },

    {
        movie_aid: 8,
        movie_title: "Missed Connection",
        movie_year: "2024",
        movie_duration: "1hr 50mins",
        movie_category: "Asian",
        movie_genre: "Drama, Romance",
        movie_summary: "After an unforgettable encounter, a hopeless romantic turns to an app to seek out a man she just met - but is he really what she's looking for?",
        movie_cast: "Miles Ocampo, Kelvin Miranda,  Chienna Filomeno",
        movie_rating: "R-20+",
        movie_image: "slider-5.webp",
        movie_is_active: true,
    },

    /* Fantasy */
    {
        movie_aid: 2,
        movie_title: "Alita: Battle Angel",
        movie_year: "2023",
        movie_duration: "1hr 30mins",
        movie_category: "Fantasy",
        movie_genre: "Adventure",
        movie_summary: " Alita is found in the scrapyard of Iron City by Ido, a compassionate cyber-doctor who takes the unconscious cyborg Alita to his clinic.",
        movie_cast: "Alita, Cybor Doctor",
        movie_rating: "R-15+",
        movie_image: "slider-2.jpg",
        movie_is_active: true,
    },

    {
        movie_aid: 3,
        movie_title: "WandaVision",
        movie_year: "2024",
        movie_duration: "2hr 30mins",
        movie_category: "Fantasy",
        movie_genre: "Drama, Superhero",
        movie_summary: "It follows Wanda Maximoff and Vision as they live an idyllic suburban life in the town of Westview, New Jersey, until their reality starts moving through different decades of sitcom homages and television tropes.",
        movie_cast: "Wanda Maximoff",
        movie_rating: "R-18+",
        movie_image: "banner-1.png",
        movie_is_active: true,
    },
    {
        movie_aid: 2,
        movie_title: "Alita: Battle Angel",
        movie_year: "2023",
        movie_duration: "1hr 30mins",
        movie_category: "Fantasy",
        movie_genre: "Adventure",
        movie_summary: " Alita is found in the scrapyard of Iron City by Ido, a compassionate cyber-doctor who takes the unconscious cyborg Alita to his clinic.",
        movie_cast: "Alita, Cybor Doctor",
        movie_rating: "R-15+",
        movie_image: "slider-2.jpg",
        movie_is_active: true,
    },

    {
        movie_aid: 3,
        movie_title: "WandaVision",
        movie_year: "2024",
        movie_duration: "2hr 30mins",
        movie_category: "Fantasy",
        movie_genre: "Drama, Superhero",
        movie_summary: "It follows Wanda Maximoff and Vision as they live an idyllic suburban life in the town of Westview, New Jersey, until their reality starts moving through different decades of sitcom homages and television tropes.",
        movie_cast: "Wanda Maximoff",
        movie_rating: "R-18+",
        movie_image: "banner-1.png",
        movie_is_active: true,
    },
    {
        movie_aid: 2,
        movie_title: "Alita: Battle Angel",
        movie_year: "2023",
        movie_duration: "1hr 30mins",
        movie_category: "Fantasy",
        movie_genre: "Adventure",
        movie_summary: " Alita is found in the scrapyard of Iron City by Ido, a compassionate cyber-doctor who takes the unconscious cyborg Alita to his clinic.",
        movie_cast: "Alita, Cybor Doctor",
        movie_rating: "R-15+",
        movie_image: "slider-2.jpg",
        movie_is_active: true,
    },

    {
        movie_aid: 3,
        movie_title: "WandaVision",
        movie_year: "2024",
        movie_duration: "2hr 30mins",
        movie_category: "Fantasy",
        movie_genre: "Drama, Superhero",
        movie_summary: "It follows Wanda Maximoff and Vision as they live an idyllic suburban life in the town of Westview, New Jersey, until their reality starts moving through different decades of sitcom homages and television tropes.",
        movie_cast: "Wanda Maximoff",
        movie_rating: "R-18+",
        movie_image: "banner-1.png",
        movie_is_active: true,
    },
    {
        movie_aid: 2,
        movie_title: "Alita: Battle Angel",
        movie_year: "2023",
        movie_duration: "1hr 30mins",
        movie_category: "Fantasy",
        movie_genre: "Adventure",
        movie_summary: " Alita is found in the scrapyard of Iron City by Ido, a compassionate cyber-doctor who takes the unconscious cyborg Alita to his clinic.",
        movie_cast: "Alita, Cybor Doctor",
        movie_rating: "R-15+",
        movie_image: "slider-2.jpg",
        movie_is_active: true,
    },

    /* Drama, Thriller, Love */
    {
        movie_aid: 4,
        movie_title: "13 Reasons Why",
        movie_year: "2017-2020",
        movie_duration: "3hr 30mins",
        movie_category: "Drama, Thriller, Love",
        movie_genre: "Drama, Romance",
        movie_summary: "Thirteen Reasons Why is a novel by Jay Asher that follows the story of Hannah Baker, a high-schooler who dies by suicide. Before her death, she records a set of tapes explaining how 13 of her classmates contributed to her decision. The novel explores themes of bullying, betrayal, and the stigma of suicide",
        movie_cast: "Clay Jensen, Katherine LanFord, Tony Padilla, Jessica Davis",
        movie_rating: "R-18+",
        movie_image: "slider-6.webp",
        movie_is_active: true,
    },

    {
        movie_aid: 5,
        movie_title: "The In Between",
        movie_year: "2022",
        movie_duration: "2hr 30mins",
        movie_category: "Drama, Thriller, Love",
        movie_genre: "Drama, Romance",
        movie_summary: "The In Between is a supernatural love story that centers on Tessa an aspiring photographer who is trying to make contact with Skylar (Kyle Allen), her boyfriend who died in a car accident",
        movie_cast: "Joey King, Kyle Allen",
        movie_rating: "R-18+",
        movie_image: "slider-7.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 4,
        movie_title: "13 Reasons Why",
        movie_year: "2017-2020",
        movie_duration: "3hr 30mins",
        movie_category: "Drama, Thriller, Love",
        movie_genre: "Drama, Romance",
        movie_summary: "Thirteen Reasons Why is a novel by Jay Asher that follows the story of Hannah Baker, a high-schooler who dies by suicide. Before her death, she records a set of tapes explaining how 13 of her classmates contributed to her decision. The novel explores themes of bullying, betrayal, and the stigma of suicide",
        movie_cast: "Clay Jensen, Katherine LanFord, Tony Padilla, Jessica Davis",
        movie_rating: "R-18+",
        movie_image: "slider-6.webp",
        movie_is_active: true,
    },

    {
        movie_aid: 5,
        movie_title: "The In Between",
        movie_year: "2022",
        movie_duration: "2hr 30mins",
        movie_category: "Drama, Thriller, Love",
        movie_genre: "Drama, Romance",
        movie_summary: "The In Between is a supernatural love story that centers on Tessa an aspiring photographer who is trying to make contact with Skylar (Kyle Allen), her boyfriend who died in a car accident",
        movie_cast: "Joey King, Kyle Allen",
        movie_rating: "R-18+",
        movie_image: "slider-7.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 4,
        movie_title: "13 Reasons Why",
        movie_year: "2017-2020",
        movie_duration: "3hr 30mins",
        movie_category: "Drama, Thriller, Love",
        movie_genre: "Drama, Romance",
        movie_summary: "Thirteen Reasons Why is a novel by Jay Asher that follows the story of Hannah Baker, a high-schooler who dies by suicide. Before her death, she records a set of tapes explaining how 13 of her classmates contributed to her decision. The novel explores themes of bullying, betrayal, and the stigma of suicide",
        movie_cast: "Clay Jensen, Katherine LanFord, Tony Padilla, Jessica Davis",
        movie_rating: "R-18+",
        movie_image: "slider-6.webp",
        movie_is_active: true,
    },

    {
        movie_aid: 5,
        movie_title: "The In Between",
        movie_year: "2022",
        movie_duration: "2hr 30mins",
        movie_category: "Drama, Thriller, Love",
        movie_genre: "Drama, Romance",
        movie_summary: "The In Between is a supernatural love story that centers on Tessa an aspiring photographer who is trying to make contact with Skylar (Kyle Allen), her boyfriend who died in a car accident",
        movie_cast: "Joey King, Kyle Allen",
        movie_rating: "R-18+",
        movie_image: "slider-7.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 4,
        movie_title: "13 Reasons Why",
        movie_year: "2017-2020",
        movie_duration: "3hr 30mins",
        movie_category: "Drama, Thriller, Love",
        movie_genre: "Drama, Romance",
        movie_summary: "Thirteen Reasons Why is a novel by Jay Asher that follows the story of Hannah Baker, a high-schooler who dies by suicide. Before her death, she records a set of tapes explaining how 13 of her classmates contributed to her decision. The novel explores themes of bullying, betrayal, and the stigma of suicide",
        movie_cast: "Clay Jensen, Katherine LanFord, Tony Padilla, Jessica Davis",
        movie_rating: "R-18+",
        movie_image: "slider-6.webp",
        movie_is_active: true,
    },

    {
        movie_aid: 5,
        movie_title: "The In Between",
        movie_year: "2022",
        movie_duration: "2hr 30mins",
        movie_category: "Drama, Thriller, Love",
        movie_genre: "Drama, Romance",
        movie_summary: "The In Between is a supernatural love story that centers on Tessa an aspiring photographer who is trying to make contact with Skylar (Kyle Allen), her boyfriend who died in a car accident",
        movie_cast: "Joey King, Kyle Allen",
        movie_rating: "R-18+",
        movie_image: "slider-7.jpg",
        movie_is_active: true,
    },
]